windows.options(width=480, height=480)
data<-read.csv("household_power_consumption.txt",header = TRUE, stringsAsFactors = FALSE,sep = ";",na.strings = "?")
data$Date <- as.Date(data$Date, format = "%d/%m/%Y")
data1<-subset(data,data$Date=="2007-02-01"|data$Date=="2007-02-02")
DateTime<-paste(data1$Date,data1$Time)
DateTime <- strptime(DateTime, format = "%Y-%m-%d %H:%M:%S")
with(data1,plot(c(DateTime, DateTime, DateTime),c(Sub_metering_1, Sub_metering_2, Sub_metering_3),type=c("l","l","l"), col=c("Black","Red","Blue")))
with(data1,lines(c(DateTime, DateTime, DateTime),c(Sub_metering_1, Sub_metering_2, Sub_metering_3),type = c("l","l","l")))
legend("topright",pch=1,col = c("Black","Red","Blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
dev.copy(png,file="plot3.png") 
